### ISSUE TITLE
Uncaught promise error

### ISSUE THREAD

**Issue by ghost** [UnseenFaith/komada#352]
### Version of Komada
v0.20.10

### Are core files modified?
No.

### Describe the problem
Uncaught promise error when trying to send a message in a channel that the bot can see but cannot talk in. This happens with System Commands and custom commands.

### Expected Behaviour
The error should be caught or handled in some way.

### Actual Behaviour
This Error is given:
`Uncaught Promise Error:
DiscordAPIError: Missing Permissions
    at item.request.gen.end (/root/node_modules/komada/node_modules/discord.js/src/rest/handlers/RequestHandler.js:52:65)
    at then (/root/node_modules/komada/node_modules/snekfetch/src/index.js:263:21)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
`

### Steps to Reproduce.
1. Make a text channel that the bot can read messages, but not send messages.
2. Use a command in that channel and receive an error in the console.

### Another uncaught promise error (dont know how to reproduce this one)
`Uncaught Promise Error:
  TypeError: Cannot read property 'missing' of null
  at Object.exports.run (/komada/src/inhibitors/missingBotPermissions.js:22:88)`

**Comment by CyberiumShadow** [comment]
First uncaught error can be reproduced. 
Have yet to find a way  to reproduce the second error.

@UnseenFaith @kyranet @bdistin 
Thoughts?
