### ISSUE TITLE
Error On Opening

### ISSUE THREAD

**Issue by ecinteza** [UnseenFaith/komada#374]
### Version of Komada
0.21.1

### Are core files modified?
No

### Describe the problem

...\node_modules\komada\src\classes\argResolver.js:32
  async msg(arg, currentUsage, possible, repeat, msg) {
        ^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (...\node_modules\komada\src\index.js:2:16)

### Expected Behaviour
To not be an error

### Actual Behaviour
Is an error

### Steps to Reproduce.
I just reinstalled komada after a long time, and appears that :<

**Comment by kyranet** [comment]
You need at least Node.js 8.1.0 minimum to run Komada. Install Node.js 8.9.0 LTS here: https://nodejs.org/en/download/
